### ISSUE TITLE
makemap is shutting down the interactive backend when launched in SEPAL

### ISSUE THREAD

**Issue by 12rambau** [ghislainv/riskmapjnr#4]
still in the same example (https://github.com/12rambau/riskmapjnr/blob/main/riskmapjnr.ipynb) I get a weird behavior from matplotlib. 

In the first cells everything goes as expected but after a call to `makemap` I get the following warning: 
```
No display found. Using non-interactive Agg backend.
```

Which of course prevents any display of matplotlib results downstream. I assume it's due to the SEPAL environment but I'm curious where do you use matplotlib in the computation steps ?

**Comment by ghislainv** [comment]
This warning is probably due to lines 17-20 in [__init.py__](https://github.com/ghislainv/riskmapjnr/blob/main/riskmapjnr/__init__.py):

``` python
# Use Agg if no display found
if os.name == "posix" and "DISPLAY" not in os.environ:
    print("no display found. Using non-interactive Agg backend")
    matplotlib.use("Agg")
```

But if I am not wrong, you should get this warning during the import.

matplotlib is used to draw several plots during the computation, eg:
- the relationship between cumulative deforestation and distance to forest edge.
- the relationship between wRMSE and window size.

If I remember well, I needed to specify the Agg backend to obtain plots with matplotlib in case there were no display (eg. Sepal).

Would you suggest another approach?

**Comment by 12rambau** [comment]
I need to make some checks from my side but from what I remembered, matplotlib is way much more clever than us to guess what backend is available. As I now realize that you run async jobs it may require further analysis.

Let me come back to you with tests on SEPAL

**Comment by ghislainv** [comment]
Maybe the best option is to remove `matplotlib.use("Agg")` from the `__init__.py` file and let the user specify the backend manually at the start of the analysis with the following lines.

``` python
import os
import matplotlib

# Use Agg if no display found
if os.name == "posix" and "DISPLAY" not in os.environ:
    matplotlib.use("Agg")
```

For the moment, I have commented this part in [`__init__.py`](https://github.com/ghislainv/riskmapjnr/blob/main/riskmapjnr/__init__.py).
